version: "3.3" 

services:
  rp:
#    build: .
    image: theredfoxlee/resource_protector:1.0
    ports:
      - "80:8000"
    environment:
      - DJANGO_CUSTOM_DEBUG=1
      - AWS_STORAGE_BUCKET_NAME=rpstorage
      - AWS_S3_ENDPOINT_URL=http://s3:8333
      - POSTGRES_DB_HOST=db
      - POSTGRES_DB_PORT=5432
      - POSTGRES_DB_NAME=rpdatabase
      - POSTGRES_DB_USER=admin
      - POSTGRES_DB_PASSWORD=admin
      - ENTRYPOINT_DELAY_S=10
    networks:
      - rp
    depends_on:
      - s3
  s3:
    image: chrislusf/seaweedfs:2.54
    ports:
      - "8333:8333"
    networks:
      - rp
    command: server -s3 -volume.max=1
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=rpdatabase
    networks:
      - rp

networks:
  rp:
    driver: bridge
